services:
  database:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=trip-todo"
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=hello_test"
