spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/trip_todo
        username: matchalab_admin_test
        password: hello_test
    jpa:
        show-sql: true
        database: postgresql
        hibernate:
            ddl-auto: create-drop
    ssl:
        bundle:
            pem:
                mybundle:
                    truststore:
                        certificate: classpath:certs/ap-northeast-2-root.pem
    cloud:
        gcp:
            project-id: travel-checklist-461608
            credentials:
                location: classpath:/certs/gc-service-account-key.json
cors:
    client-url: http://localhost:8081
server:
    port: 5000
