spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/trip_todo
        username: matchalab_admin_test
        password: hello_test
    jpa:
        show-sql: true
        database: postgresql
        hibernate:
            ddl-auto: create-drop
server:
    port: 8080