networks:
  app-network:
    name: load-test-network
    external: true
    
services:
  target-spring-app:
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 2s
      retries: 3
    environment:
      SPRING_PROFILES_ACTIVE: dev,no-security,load-test
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_AI_OPENAI_BASEURL: http://llm-mock-server:8081
      # JVM heap memory allocation (1.25GB)
      JAVA_TOOL_OPTIONS: -Xms640m -Xmx640m -XX:MaxMetaspaceSize=128m -XX:ReservedCodeCacheSize=64m -XX:MaxDirectMemorySize=64m
      MANAGEMENT_METRICS_TAGS_TEST_ID: ${MANAGEMENT_METRICS_TAGS_TEST_ID}
      MANAGEMENT_METRICS_TAGS_ITERATION: ${MANAGEMENT_METRICS_TAGS_ITERATION}
    deploy:
      resources:
        limits:
          memory: 1G #1GB
    cpuset: "2,3"